### PR TITLE
Allow string to be passed into config as well as constant, default should be string.

### PR DESCRIPTION
**Pull request by mrsweaters**
Fixes: https://github.com/prey/gdpr_rails/issues/31

We should not load the constant directly in the initializer as this can break other dependencies.

Discussed in detail here: https://github.com/rails/rails/issues/32933#issuecomment-395919084

### CODE REVIEW

**Comment by michelson** [comment]
Thanks for this fix mr @mrsweaters , we will release asap

**Comment by mrsweaters** [comment]
Thanks!

**Comment by beneggett** [comment]
It appears the same initialization issues occur on admin_user if a different class is used for `Admin` than `User`. 

Also, if Admin user is stringified, it breaks in different places. 

When I get some more time I'll try to take a look into it

**Comment by TeamRainless** [comment]
> It appears the same initialization issues occur on admin_user if a different class is used for `Admin` than `User`.
> 
> Also, if Admin user is stringified, it breaks in different places.
> 
> When I get some more time I'll try to take a look into it

Still having this issue. EXACTLY these circumstances.  I have regular users as admin users with just a "superadmin" boolean. I keep getting the "has_one_attached" error.  Any steps to work around this?

**Pull request merged**
