### PR TITLE
Rails 6 minor and patch

### PR DESCRIPTION
**Pull request by mrsweaters**
This will allow us to update Rails to the recent security-patched versions of Rails.

Closes: https://github.com/prey/gdpr_rails/issues/44

### CODE REVIEW

**Comment by michelson** [comment]
@mrsweaters Thanks! 
could you commit the appraisals Gemfile.lock in order to CI to pass

Thanks!

**Comment by mrsweaters** [comment]
I updated the appraisal but now I'm getting an issue looking for a manifest file:

```sh
Failure/Error: //= link terms_manifest.js
     ActionView::Template::Error:
       couldn't find file 'terms_manifest.js'
```

I see a policy_manager_manifest.js but no terms_manifest.js.

**Comment by masonhensley** [comment]
> I updated the appraisal but now I'm getting an issue looking for a manifest file:
> 
> ```shell
> Failure/Error: //= link terms_manifest.js
>      ActionView::Template::Error:
>        couldn't find file 'terms_manifest.js'
> ```
> 
> I see a policy_manager_manifest.js but no terms_manifest.js.

@mrsweaters - I pulled the repo down and couldn't find any other reference besides that failure in `gdpr_rails/spec/dummy/app/assets/config/manifest.js` that mentions 'terms_manifest.js' ... other than deleting that line, not sure what to do unless @michelson has any guidance.

Thanks for the contribution! 🥇

**Comment by mrsweaters** [comment]
@michelson Oh interesting! Yeah maybe it is cached in Travis somewhere.

**Comment by masonhensley** [comment]
@mrsweaters - would you be able to make a one line change to the MR so that Travis is retriggered? 🤞 everything would be green then. 

If you're too busy, do you mind me forking your branch and submitting it as a new MR to get it to green?

Thanks again

**Pull request closed without merging**
