### PR TITLE
Rails 6 active storage

### PR DESCRIPTION
**Pull request by michelson**
- adds rails 6 support
- adds active storage support
- adds a legacy mode for paperclip
- a slim matrix for travis ci

### CODE REVIEW

**Comment by michelson** [comment]
#38

**Comment by mrsweaters** [comment]
Rails 6 has been released, is this ready to merge in?

**Comment by michelson** [comment]
Hi , I've updated dependences on the rails6 (from 6.0.0-rc1 to 6.0.0) in appraisal gemfile in order to release. Unfortunately there is a failing build on travis. it seems the problem is from travis platform but I will dig further on this. 

meanwhile you can try this branch on your rails 6 application.

**Comment by michelson** [comment]
released in rubygems as 0.5.0 version

**Comment by mrsweaters** [comment]
Sweet! Yeah I didn't see any issues in my app. Thanks for this!

**Pull request merged**
